import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { auth } from "@/firebase";
import ProtectedRoutes from "@/components/ProtectedRoutes";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Dashboard from "./dashboard";
import { signOut } from "firebase/auth";
import Welcome from "./welcome";

export default function Home() {
  const router = useRouter();
  
  // use on auth changed
  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      if (user) {
        router.push("/");
      }
    });
    return () => unsubscribe();
  }, [auth]);

  return (
    <>
      <Head>
        <title>Submission for Soheil Feizi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* when a user is signed in */}
        {auth?.currentUser?.uid ? (
          <ProtectedRoutes>
            <Dashboard />
          </ProtectedRoutes>
        ) : (
          <Welcome />
        )}
      </div>
    </>
  );
}
